version: "3"
services:
  app:
    container_name: app
    build: app/
    command: python3 -u app/main.py --host 5000
    volumes:
    - .:/app
    ports:
      - "5000:5000"
    networks:
      - frontend

 

networks:
  frontend:
    driver: "bridge"